Adapted periTest.py to look at my data. Currently it doesn't work.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-68-1433e5b646d3> in <module>
----> 1 st = states.ImageState(im, [particles, illumination, background, point_spread_function, offset], mdl=model)

~/anaconda3/lib/python3.7/site-packages/peri-0.1.2-py3.7.egg/peri/states.py in __init__(self, image, comps, mdl, sigma, priors, pad, model_as_data)
    547         self.model_as_data = model_as_data
    548 
--> 549         comp.ComponentCollection.__init__(self, comps=comps)
    550 
    551         self.set_model(mdl=mdl)

~/anaconda3/lib/python3.7/site-packages/peri-0.1.2-py3.7.egg/peri/comp/comp.py in __init__(self, comps, field_reduce_func, category)
    378         self.field_reduce_func = field_reduce_func
    379 
--> 380         self.setup_params()
    381         self.setup_passthroughs()
    382         self._parent = None

~/anaconda3/lib/python3.7/site-packages/peri-0.1.2-py3.7.egg/peri/comp/comp.py in setup_params(self)
    399 
    400         for c in self.comps:
--> 401             c.register(self)
    402 
    403             if not isinstance(c, (Component, ComponentCollection)):

TypeError: register() missing 1 required positional argument: 'obj'